# Generated by Django 2.1.15 on 2022-05-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220526_0008'),
        ('gestion', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Facility'),
        ),
    ]
