# Generated by Django 4.0.4 on 2022-05-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_category_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
