# Generated by Django 2.1.15 on 2022-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facility_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isFacility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
