# Generated by Django 2.1.15 on 2022-05-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_isfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='isFacility',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
