# Generated by Django 2.1.15 on 2022-05-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220521_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.AddField(
            model_name='myuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
