# Generated by Django 4.0.4 on 2022-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220526_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='categories',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
